import axios from 'axios';

// Get all books
export const getAllBooks = async () => {
  const response = await axios.get('https://book-library-98oa9wpar-shubhamrozers-projects.vercel.app/api/books/books');
  return response.data;
};

// Get all users
export const getAllUsers = async () => {
  const response = await axios.get('https://book-library-98oa9wpar-shubhamrozers-projects.vercel.app/api/books/users');
  return response.data;
};

// Search for a book by name
export const searchBooks = async (bookName) => {
  const response = await axios.get(`https://book-library-98oa9wpar-shubhamrozers-projects.vercel.app/api/books/search?name=${bookName}`);
  return response.data;
};

// Filter books by rent range
export const filterBooksByRent = async (minRent, maxRent) => {
  const response = await axios.get(`https://book-library-98oa9wpar-shubhamrozers-projects.vercel.app/api/books/filter-by-rent?minRent=${minRent}&maxRent=${maxRent}`);
  return response.data;
};

// Issue a book to a user
export const issueBook = async (bookName, userName, issueDate) => {
  const response = await axios.post('https://book-library-98oa9wpar-shubhamrozers-projects.vercel.app/api/books/issue-book', {
    bookName, userName, issueDate,
  });
  return response.data;
};

// Return a book and calculate rent
export const returnBook = async (bookName, userName, returnDate) => {
  const response = await axios.post('https://book-library-98oa9wpar-shubhamrozers-projects.vercel.app/api/books/return-book', {
    bookName, userName, returnDate,
  });
  return response.data;
};

// Get total rent generated by a book
export const getTotalRent = async (bookName) => {
  const response = await axios.get(`https://book-library-98oa9wpar-shubhamrozers-projects.vercel.app/api/books/total-rent?bookName=${bookName}`);
  return response.data;
};

// Get all books issued by a specific user
export const getIssuedBooksByUser = async (userName) => {
  const response = await axios.get(`https://book-library-98oa9wpar-shubhamrozers-projects.vercel.app/api/books/issued-books?userName=${userName}`);
  return response.data;
};

// Get books issued within a date range
export const getBooksInDateRange = async (startDate, endDate) => {
  const response = await axios.get(`https://book-library-98oa9wpar-shubhamrozers-projects.vercel.app/api/books/issued-in-date-range?startDate=${startDate}&endDate=${endDate}`);
  return response.data;
};
